language: go

go:
  - 1.3
  - 1.4
  - 1.5

before_install:
  - gem install fpm
  - gem install package_cloud

install: make deps

script:
  - make test
  - make build
  - mkdir -p dist/usr/bin
  - mv dist/s3pgbackups dist/usr/bin/s3pgbackups
  - fpm -s dir -t deb -n s3pgbackups -v 0.0.2 -C dist -p s3pgbackups_VERSION_ARCH.deb -m greg@sigterm.sh --description "Amazon S3 PostgreSQL backups tool." --url https://github.com/gregarmer/s3pgbackups usr/bin

deploy:
  provider: packagecloud
  repository: "packages"
  username: "gregarmer"
  dist: "debian/jessie"
  on:
    branch: master
    go: '1.5'
